### ISSUE TITLE
make load image from URI

### ISSUE THREAD

**Issue by adityapp** [bccfilkom/gridmenu#20]

**Comment by syariefnoorp** [comment]
you don't need make load image from URI, cause you just need input image type Drawable or Bitmap :v @adityapp

**Comment by gifff** [comment]
Using Bitmap in the MenuItem model makes it universal to use and this
project loosely-coupled from image loader dependencies. But the drawback is
that it's more complicated to use.

>

**Comment by febryanasaperdana** [comment]
Using or loading drawable or bitmap directly may cause memory issues to the app as loading them requires significant memory usage. Even if it is not necessary or there is no urgency right now, it might be good to create a utility or helper class that lets users to pass their preferred image loaders (Picasso, Glide, Fresco, UniversalImageLoader, etc.). Therefore, the "universal" term can be persisted, as users can still freely use the dependency as how they want it. Moreover, image loaders can be a good solution in case users need to load image from various options or dealing with image loading problems.

**Comment by adityapp** [comment]
please, attach a memory issue for us to consider @febryanasaperdana

**Comment by febryanasaperdana** [comment]
@adityapp As I have not tried this dependency in any of my apps or projects, I can not attach any memory issues related with the usage of this dependency right now, especially in the case of loading drawable or bitmap directly. Popular memory issues in most Android apps dealing with image loading such as the OutOfMemory (OOM) exception, high heap size, unresponsive/slow UI, may occur depending on the usage and configuration by the users: caching strategy, the bitmap (image) dimension, etc.

The above comment by me was meant to be a suggestion to previous comments made by @gifff @syariefnoorp . Image loaders have such a proven mechanism that makes image loading a breeze, as well as opening the possibility to load image from URI per this issue request.

I might fork and try this dependency later and see if I can produce any memory issues regarding this, as well as exploring various image loading options.

**Comment by gifff** [comment]
Well, I guess there's a misunderstanding in your point of view. What I
meant is that we provide a mechanism to load a Bitmap object to the
ImageView and leave the image-loading mechanism to the users. So if they
want to use existing image loader such as Glide, they have to implement it
themselves and piped the loaded image to our interface (after transforming
to Bitmap object).

**Comment by febryanasaperdana** [comment]
@gifff Thanks for the clarification, now the air has been cleared up. I have not tried this dependency hence I apologize if my answer is very opinionated. The library is great and there is much room for improvement.

**Comment by gifff** [comment]
This feature is already implemented in #24
